export const BUSINESS_EMAILS = {
  retail: 'retail@test.com',
  barber: 'barber@test.com',
}

export const DOC_TYPES = {
  invoices:          { label_ar:'فاتورة مبيع',      label_en:'Sales Invoice',      prefix:'INV', store:'invoices',      partyLabel_ar:'العميل',  partyLabel_en:'Customer',  icon:'🧾', parties:['شركة الأمل التجارية','مؤسسة النجاح','شركة الخليج','محلات السعادة','مجموعة الفجر','التجارية للأعمال'] },
  'sales-return':    { label_ar:'مرتجع مبيعات',     label_en:'Sales Return',       prefix:'SR',  store:'salesReturns',  partyLabel_ar:'العميل',  partyLabel_en:'Customer',  icon:'↩️', parties:['شركة الأمل التجارية','مؤسسة النجاح','شركة الخليج','محلات السعادة'] },
  orders:            { label_ar:'طلبية',             label_en:'Order',              prefix:'ORD', store:'orders',        partyLabel_ar:'العميل',  partyLabel_en:'Customer',  icon:'📑', parties:['شركة الأمل التجارية','مؤسسة النجاح','شركة الخليج','محلات السعادة'] },
  purchases:         { label_ar:'فاتورة شراء',       label_en:'Purchase Invoice',   prefix:'PUR', store:'purchases',     partyLabel_ar:'المورد',  partyLabel_en:'Supplier',  icon:'🛒', parties:['مورد الإلكترونيات','مورد القرطاسية','مورد الأثاث','مورد المعدات'] },
  'purchases-return':{ label_ar:'مرتجع مشتريات',    label_en:'Purchase Return',    prefix:'PR',  store:'purchReturns',  partyLabel_ar:'المورد',  partyLabel_en:'Supplier',  icon:'↩️', parties:['مورد الإلكترونيات','مورد القرطاسية','مورد الأثاث'] },
}

export const SIDEBAR_MENUS = {
  barber: [
    { icon:'📊', label:'لوحة التحكم',     page:'dashboard' },
    { icon:'✂️', label:'الخدمات',         page:'services' },
    { icon:'👥', label:'الموظفون',         page:'employees' },
    { icon:'💰', label:'العمولات',         page:'commissions' },
    { icon:'📅', label:'الحجوزات',         page:'reservations' },
    { icon:'👤', label:'العملاء',          page:'customers' },
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'🧴', label:'المستلزمات',       page:'supplies' },
    { icon:'💡', label:'الفواتير الثابتة', page:'bills' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
  retail: [
    { icon:'📊', label:'لوحة التحكم',      page:'dashboard' },
    { icon:'👤', label:'العملاء',          page:'customers' },
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'↩️', label:'مرتجع مبيعات',    page:'sales-return' },
    { icon:'📑', label:'طلبيات',           page:'orders' },
    { icon:'🛒', label:'فاتورة شراء',      page:'purchases' },
    { icon:'📋', label:'سجل المشتريات',    page:'purchases-list' },
    { icon:'↩️', label:'مرتجع مشتريات',   page:'purchases-return' },
    { icon:'📦', label:'أصناف',            page:'items' },
    { icon:'📈', label:'كشف المخزون',      page:'stock-report' },
    { icon:'🏭', label:'المخازن',          page:'warehouse' },
    { icon:'📒', label:'دليل الحسابات',    page:'accounts' },
    { icon:'🔍', label:'كشف حساب',         page:'account-ledger' },
    { icon:'⚖️', label:'ميزان المراجعة',   page:'trial-balance' },
    { icon:'✏️', label:'القيود المحاسبية', page:'journal-entries' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
  building_materials: [
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'↩️', label:'مرتجع مبيعات',    page:'sales-return' },
    { icon:'🛒', label:'فاتورة شراء',      page:'purchases' },
    { icon:'📋', label:'سجل المشتريات',    page:'purchases-list' },
    { icon:'↩️', label:'مرتجع مشتريات',   page:'purchases-return' },
    { icon:'📦', label:'أصناف',            page:'items' },
    { icon:'📒', label:'دليل الحسابات',    page:'accounts' },
    { icon:'🔍', label:'كشف حساب',         page:'account-ledger' },
    { icon:'⚖️', label:'ميزان المراجعة',   page:'trial-balance' },
    { icon:'✏️', label:'القيود المحاسبية', page:'journal-entries' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
  auto_parts: [
    { icon:'📊', label:'لوحة التحكم',      page:'dashboard' },
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'↩️', label:'مرتجع مبيعات',    page:'sales-return' },
    { icon:'📑', label:'طلبيات',           page:'orders' },
    { icon:'🛒', label:'فاتورة شراء',      page:'purchases' },
    { icon:'📋', label:'سجل المشتريات',    page:'purchases-list' },
    { icon:'↩️', label:'مرتجع مشتريات',   page:'purchases-return' },
    { icon:'📦', label:'أصناف',            page:'items' },
    { icon:'📈', label:'كشف المخزون',      page:'stock-report' },
    { icon:'🏭', label:'المخازن',          page:'warehouse' },
    { icon:'📒', label:'دليل الحسابات',    page:'accounts' },
    { icon:'🔍', label:'كشف حساب',         page:'account-ledger' },
    { icon:'⚖️', label:'ميزان المراجعة',   page:'trial-balance' },
    { icon:'✏️', label:'القيود المحاسبية', page:'journal-entries' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
}

export const i18n = {
  AR: {
    // General
    loading:'جاري التحميل...',save_btn:'حفظ',cancel_btn:'إلغاء',delete_btn:'حذف',edit_btn:'تعديل',print_btn:'طباعة',export_btn:'تصدير',view_all:'عرض الكل',no_data:'لا توجد بيانات',
    // Status
    status_paid:'مدفوعة',status_unpaid:'غير مدفوعة',status_partial:'جزئي',status_cancelled:'ملغاة',status_low:'منخفض',status_ok:'متوفر',status_active:'نشط',
    pay_cash:'نقداً',pay_bank:'تحويل بنكي',pay_check:'شيك',
    // Common table headers
    th_number:'الرقم',th_date:'التاريخ',th_total:'الإجمالي',th_status:'الحالة',th_action:'إجراء',th_debit:'مدين',th_credit:'دائن',th_balance:'الرصيد',th_desc:'البيان',th_name:'الاسم',th_code:'كود',th_amount:'المبلغ',th_phone:'الهاتف',
    // Common labels
    lbl_date:'التاريخ',lbl_amount:'المبلغ',lbl_desc:'البيان',lbl_name:'الاسم',lbl_phone:'الهاتف',
    // Sidebar
    biz_barber:'صالون حلاقة',biz_retail:'تجزئة',logout:'تسجيل الخروج',
    nav_dashboard:'لوحة التحكم',nav_services:'الخدمات',nav_employees:'الموظفون',nav_reservations:'الحجوزات',
    nav_invoices:'فاتورة مبيع',nav_inv_list:'سجل الفواتير',nav_sales_return:'مرتجع مبيعات',nav_orders:'طلبيات',
    nav_purchases_inv:'فاتورة شراء',nav_pur_list:'سجل المشتريات',nav_purchases_return:'مرتجع مشتريات',
    nav_items:'أصناف',nav_stock_report:'كشف المخزون',nav_warehouse:'المخازن',
    nav_accounts:'دليل الحسابات',nav_ledger:'كشف حساب',nav_trial_balance:'ميزان المراجعة',nav_journal_entries:'القيود المحاسبية',
    nav_supplies:'المستلزمات',nav_bills:'الفواتير الثابتة',nav_receipt:'سند قبض',nav_payment:'سند صرف',nav_company_settings:'بيانات الشركة',
    // Login
    login_subtitle:'نظام إدارة الأعمال',login_email:'البريد الإلكتروني',login_password:'كلمة المرور',
    login_btn:'تسجيل الدخول',login_loading:'جاري تسجيل الدخول...',
    login_error_empty:'الرجاء إدخال البريد الإلكتروني وكلمة المرور',login_error_wrong:'البريد الإلكتروني أو كلمة المرور غير صحيحة',
    // Trading Dashboard
    dashboard_title:'لوحة التحكم',new_invoice_btn:'فاتورة جديدة',
    total_revenue:'إجمالي الإيرادات',paid_invoices:'الفواتير المدفوعة',inventory_items:'أصناف المخزون',low_stock_count:'أصناف منخفضة',
    stat_rev_sub:'↑ 12% من الشهر الماضي',total_units_sub:'وحدة إجمالية',needs_reorder:'تحتاج لإعادة طلب',out_of:'من أصل',
    sales_chart_title:'مبيعات الأشهر الستة',low_stock_title:'أصناف منخفضة المخزون',
    stock_ok:'✅ المخزون في وضع جيد',recent_invoices_title:'آخر الفواتير',top_customers_title:'أكبر العملاء',no_invoices:'لا توجد فواتير بعد',
    // Barber Dashboard
    new_reservation_btn:'حجز جديد',supplies_btn:'مستلزم',
    month_revenue:'إيرادات هذا الشهر',month_expenses:'مصاريف هذا الشهر',net_profit:'صافي الربح',today_cuts:'قطعات اليوم',
    done_services:'خدمة منجزة',supplies_bills_sub:'مستلزمات + فواتير ثابتة',profit_label:'ربح',loss_label:'خسارة',
    today_reservations:'حجوزات اليوم',no_today_reservations:'لا توجد حجوزات اليوم',
    barber_performance:'أداء الحلاقين هذا الشهر',no_employees:'لا يوجد موظفون',cuts_unit:'قطعة',due_commission:'عمولة مستحقة',
    popular_services:'الخدمات الأكثر طلباً',no_data_yet:'لا توجد بيانات بعد',times_unit:'مرة',
    financial_summary:'ملخص مالي',month_revenue_summary:'إيرادات الشهر',supplies_cost:'مستلزمات',fixed_bills_label:'فواتير ثابتة',
    res_pending:'قيد الانتظار',res_confirmed:'مؤكد',res_done:'منجز',res_cancelled:'ملغى',
    // Items
    items_title:'أصناف المخزون',new_item_btn:'صنف جديد',search_items:'بحث باسم الصنف أو الكود...',all_categories:'كل الفئات',
    th_category:'الفئة',th_cost:'سعر الشراء',th_price:'سعر البيع',th_stock:'المخزون',th_min_stock:'الحد الأدنى',
    no_items:'لا توجد أصناف',edit_item_title:'تعديل الصنف',add_item_title:'إضافة صنف جديد',
    lbl_item_code:'الكود',lbl_item_name:'اسم الصنف',lbl_item_category:'الفئة',lbl_item_unit:'الوحدة',
    lbl_item_cost:'سعر الشراء',lbl_item_price:'سعر البيع',lbl_item_stock:'المخزون الحالي',lbl_item_min:'الحد الأدنى',lbl_item_desc:'الوصف',
    confirm_delete_item:'هل تريد حذف هذا الصنف؟',
    // Invoices list
    invoices_list_title:'سجل فواتير المبيع',search_invoices:'بحث بالرقم أو العميل...',th_customer:'العميل',th_due:'الاستحقاق',
    confirm_delete_invoice:'هل تريد حذف هذه الفاتورة؟',no_invoices_list:'لا توجد فواتير',
    // Purchases list
    purchases_list_title:'سجل المشتريات',new_purchase_btn:'فاتورة شراء جديدة',search_purchases:'بحث بالرقم أو المورد...',
    th_supplier:'المورد',no_purchases:'لا توجد فواتير مشتريات',
    // Accounts
    accounts_title:'دليل الحسابات',new_account_btn:'حساب جديد',all_types:'كل الأنواع',
    no_accounts:'لا توجد حسابات',type_asset:'أصول',type_liability:'خصوم',type_equity:'حقوق ملكية',type_revenue:'إيرادات',type_expense:'مصاريف',
    lbl_acc_code:'كود الحساب',lbl_acc_name:'اسم الحساب',lbl_acc_type:'نوع الحساب',lbl_opening_balance:'الرصيد الابتدائي',new_account_title:'حساب جديد',
    // Stock report
    stock_report_title:'كشف المخزون',total_items_label:'إجمالي الأصناف',total_units_label:'إجمالي الوحدات',
    stock_value_label:'قيمة المخزون',low_stock_label:'أصناف منخفضة',
    th_opening_stock:'المخزون الابتدائي',th_incoming:'وارد',th_outgoing:'صادر',th_current_stock:'المخزون الحالي',th_value:'القيمة',
    // Warehouse
    warehouses_title:'المخازن',new_warehouse_btn:'مخزن جديد',no_warehouses:'لا توجد مخازن',new_warehouse_title:'مخزن جديد',
    lbl_warehouse_name:'اسم المخزن',lbl_location:'الموقع',lbl_manager:'المسؤول',
    // Ledger
    ledger_title:'كشف حساب',lbl_account:'الحساب',select_account:'-- اختر حساب --',from_date:'من تاريخ',view_btn:'عرض',
    opening_balance_row:'رصيد أول المدة',no_movements:'لا توجد حركات في هذه الفترة',
    // Trial balance
    trial_balance_title:'ميزان المراجعة',trial_balance_sub:'ميزان المراجعة',total_label:'الإجمالي',
    // Journal entries
    journal_title:'القيود المحاسبية',new_entry_btn:'قيد جديد',no_entries:'لا توجد قيود',new_entry_title:'قيد محاسبي جديد',
    lbl_debit_acc:'حساب المدين',lbl_credit_acc:'حساب الدائن',select_placeholder:'-- اختر --',
    // Receipt voucher
    receipt_title:'سند قبض',new_receipt_title:'سند قبض جديد',lbl_voucher_no:'رقم السند',lbl_received_from:'المستلم منه',
    save_voucher_btn:'حفظ السند',recent_vouchers:'آخر السندات',th_from:'من',no_vouchers:'لا توجد سندات',
    // Payment voucher
    payment_title:'سند صرف',new_payment_title:'سند صرف جديد',lbl_paid_to:'المصروف إليه',th_to:'إلى',
    // Services
    services_title:'الخدمات',new_service_btn:'خدمة جديدة',th_service:'الخدمة',th_base_price:'السعر الأساسي',th_duration:'المدة',
    no_services:'لا توجد خدمات',no_services_hint:'أضف خدماتك مثل: قصة شعر، تحديد لحية، غسيل شعر',svc_active:'نشطة',svc_inactive:'موقوفة',edit_service_title:'تعديل الخدمة',new_service_title:'خدمة جديدة',
    lbl_service_name:'اسم الخدمة',service_name_placeholder:'مثال: قصة شعر',lbl_base_price:'السعر الأساسي ($)',lbl_duration_min:'المدة (دقيقة)',min_abbr:'د',
    lbl_junior_price:'سعر Junior ($)',lbl_senior_price:'سعر Senior ($)',lbl_master_price:'سعر Master ($)',
    // Employees
    employees_title:'الموظفون',new_employee_btn:'موظف جديد',no_employees_data:'لا يوجد موظفون',
    emp_count:'عدد الموظفين',month_cuts:'قطعات هذا الشهر',month_rev_label:'إيرادات هذا الشهر',
    th_emp_level:'المستوى',th_salary_type:'نوع الراتب',th_base_salary:'الراتب',th_commission_pct:'العمولة%',th_month_cuts:'قطعات الشهر',th_due:'المستحق',
    edit_employee_title:'تعديل الموظف',new_employee_title:'موظف جديد',
    lbl_emp_name:'الاسم',lbl_emp_level:'المستوى',lbl_salary_type:'نوع الراتب',lbl_base_salary:'الراتب الأساسي ($)',lbl_commission_rate:'نسبة العمولة (%)',
    salary_commission:'عمولة فقط',salary_salary_commission:'راتب + عمولة',salary_salary:'راتب ثابت',
    // Reservations
    reservations_title:'الحجوزات',search_customer:'بحث باسم العميل...',all_statuses:'كل الحالات',
    th_res_customer:'العميل',th_res_service:'الخدمة',th_res_employee:'الحلاق',th_res_time:'الوقت',th_res_price:'السعر',
    no_reservations:'لا توجد حجوزات',edit_reservation_title:'تعديل الحجز',new_reservation_title:'حجز جديد',
    lbl_customer_name:'اسم العميل',lbl_service:'الخدمة',lbl_employee:'الحلاق',lbl_time:'الوقت',lbl_price:'السعر ($)',lbl_notes:'ملاحظات',lbl_status:'الحالة',
    select_service:'-- اختر خدمة --',select_employee:'-- اختر حلاق --',
    // Supplies
    supplies_title:'المستلزمات',new_supply_btn:'إضافة مستلزم',
    month_supplies:'مصاريف هذا الشهر',total_supplies:'إجمالي المصاريف',supplies_count:'عدد السجلات',
    th_supply_cat:'الفئة',no_supplies:'لا توجد مستلزمات',new_supply_title:'إضافة مستلزم',
    lbl_supply_name:'اسم المستلزم',lbl_supply_amount:'المبلغ ($)',lbl_supply_cat:'الفئة',lbl_notes_opt:'ملاحظات',
    cat_supply:'مستلزم',cat_tool:'أداة',cat_product:'منتج',cat_other:'أخرى',
    // Bills
    bills_title:'الفواتير الثابتة',new_bill_btn:'فاتورة جديدة',
    total_unpaid:'غير مدفوعة',total_paid_label:'مدفوعة',total_bills:'إجمالي الفواتير',
    th_bill_name:'الفاتورة',th_bill_due_day:'يوم الاستحقاق',th_bill_month:'الشهر',
    no_bills:'لا توجد فواتير',new_bill_title:'فاتورة جديدة',
    lbl_bill_name:'اسم الفاتورة',lbl_bill_amount:'المبلغ ($)',lbl_bill_due_day:'يوم الاستحقاق',lbl_bill_month:'الشهر',
    bill_paid:'مدفوعة',bill_unpaid:'غير مدفوعة',unpay_btn:'إلغاء الدفع',pay_btn:'✅ دفع',
    // Company settings
    notify_saved:'تم الحفظ بنجاح ✓',notify_deleted:'تم الحذف',confirm_delete:'هل تريد الحذف؟',
    notify_bill_paid:'تم تأكيد الدفع ✅',notify_bill_unpaid:'تم إلغاء الدفع',
    notify_voucher_receipt:'تم حفظ سند القبض',notify_voucher_payment:'تم حفظ سند الصرف',
    notify_commission_error:'خطأ في تسجيل العمولة',notify_commission_saved:'تم تسجيل العمولة',notify_commission_paid:'تم تأكيد صرف العمولات ✅',
    notify_item_not_found:'الصنف غير موجود',notify_points_insufficient:'رصيد النقاط غير كافٍ',
    notify_doc_saved:'تم حفظ المستند بنجاح ✓',notify_reservation_saved:'تم حفظ الحجز بنجاح',notify_reservation_done:'تم تأكيد إنجاز الحجز ✅',
    save_error:'حدث خطأ أثناء الحفظ',company_saved:'تم حفظ إعدادات الشركة ✅',
    company_settings_title:'معطيات الشركة',save_settings_btn:'حفظ الإعدادات',
    company_data_section:'بيانات الشركة',system_settings_section:'إعدادات النظام',
    lbl_company_name_ar:'اسم الشركة (عربي)',lbl_company_name_en:'اسم الشركة (إنجليزي)',
    lbl_address:'العنوان',lbl_phone_settings:'الهاتف',lbl_email:'البريد الإلكتروني',lbl_website:'الموقع الإلكتروني',
    lbl_currency:'العملة الافتراضية',lbl_tax_rate:'نسبة الضريبة الافتراضية (%)',
    lbl_period_start:'بداية الفترة المحاسبية',lbl_period_end:'نهاية الفترة المحاسبية',lbl_reg_number:'رقم الرجيستر',
    // Doc editor
    doc_info_title:'معلومات المستند',doc_number_label:'رقم المستند',doc_due_date:'تاريخ الاستحقاق',
    doc_warehouse:'المخزن',doc_status:'الحالة',doc_party_placeholder:'اكتب اسم العميل أو المورد...',
    doc_summary_title:'ملخص المستند',doc_subtotal:'المجموع الفرعي',doc_discount_pct:'الخصم %',
    doc_vat_pct:'ضريبة VAT %',doc_notes_label:'ملاحظات',doc_items_title:'أصناف المستند',doc_add_item:'إضافة صنف',
    doc_type_invoices:'فاتورة مبيع',doc_type_sales_return:'مرتجع مبيعات',doc_type_orders:'طلبية',
    doc_type_purchases:'فاتورة شراء',doc_type_purchases_return:'مرتجع مشتريات',
    party_customer:'العميل',party_supplier:'المورد',doc_party_required:'الرجاء اختيار',
    // POS
    pay_cash_usd:'كاش USD',pay_cash_lbp:'كاش LBP',pay_card:'بطاقة',pay_loyalty:'نقاط',
    pos_search_placeholder:'ابحث عن صنف بالاسم أو الباركود...',pos_stock_label:'مخزون',
    pos_empty_cart:'ابحث عن صنف وأضفه إلى السلة',pos_col_item:'الصنف',pos_col_qty:'الكمية',
    pos_col_discount:'خصم%',pos_customer_label:'العميل',pos_phone_search:'ابحث برقم الهاتف...',
    pos_items_count_label:'عدد الأصناف',pos_item_unit:'صنف',pos_qty_unit:'وحدة',
    pos_charge_btn:'تحصيل',pos_payment_title:'الدفع',pos_pay_method_label:'طريقة الدفع',
    pos_paid_usd_label:'المبلغ المدفوع (USD)',pos_paid_lbp_label:'المبلغ المدفوع (LBP)',
    pos_processing:'جاري المعالجة...',pos_confirm_pay:'تأكيد الدفع',pos_change_label:'الباقي',
    pos_success_title:'تمت العملية بنجاح',pos_points_earned_label:'نقطة مكتسبة',
    pos_cart_empty_error:'السلة فارغة',pos_checkout_error:'خطأ في إتمام العملية',
  },
  EN: {
    loading:'Loading...',save_btn:'Save',cancel_btn:'Cancel',delete_btn:'Delete',edit_btn:'Edit',print_btn:'Print',export_btn:'Export',view_all:'View All',no_data:'No data available',
    status_paid:'Paid',status_unpaid:'Unpaid',status_partial:'Partial',status_cancelled:'Cancelled',status_low:'Low',status_ok:'In Stock',status_active:'Active',
    pay_cash:'Cash',pay_bank:'Bank Transfer',pay_check:'Check',
    th_number:'Number',th_date:'Date',th_total:'Total',th_status:'Status',th_action:'Action',th_debit:'Debit',th_credit:'Credit',th_balance:'Balance',th_desc:'Description',th_name:'Name',th_code:'Code',th_amount:'Amount',th_phone:'Phone',
    lbl_date:'Date',lbl_amount:'Amount',lbl_desc:'Description',lbl_name:'Name',lbl_phone:'Phone',
    biz_barber:'Barber Shop',biz_retail:'Retail',logout:'Logout',
    nav_dashboard:'Dashboard',nav_services:'Services',nav_employees:'Employees',nav_reservations:'Reservations',
    nav_invoices:'Sales Invoice',nav_inv_list:'Invoice Register',nav_sales_return:'Sales Return',nav_orders:'Orders',
    nav_purchases_inv:'Purchase Invoice',nav_pur_list:'Purchase Register',nav_purchases_return:'Purchase Return',
    nav_items:'Items',nav_stock_report:'Stock Report',nav_warehouse:'Warehouses',
    nav_accounts:'Chart of Accounts',nav_ledger:'Account Ledger',nav_trial_balance:'Trial Balance',nav_journal_entries:'Journal Entries',
    nav_supplies:'Supplies',nav_bills:'Fixed Bills',nav_receipt:'Receipt Voucher',nav_payment:'Payment Voucher',nav_company_settings:'Company Settings',
    login_subtitle:'Business Management System',login_email:'Email Address',login_password:'Password',
    login_btn:'Login',login_loading:'Logging in...',
    login_error_empty:'Please enter your email and password',login_error_wrong:'Invalid email or password',
    dashboard_title:'Dashboard',new_invoice_btn:'New Invoice',
    total_revenue:'Total Revenue',paid_invoices:'Paid Invoices',inventory_items:'Inventory Items',low_stock_count:'Low Stock Items',
    stat_rev_sub:'↑ 12% from last month',total_units_sub:'total units',needs_reorder:'Need reorder',out_of:'out of',
    sales_chart_title:'Last 6 Months Sales',low_stock_title:'Low Stock Items',
    stock_ok:'✅ Stock is in good condition',recent_invoices_title:'Recent Invoices',top_customers_title:'Top Customers',no_invoices:'No invoices yet',
    new_reservation_btn:'New Booking',supplies_btn:'Supply',
    month_revenue:'This Month Revenue',month_expenses:'This Month Expenses',net_profit:'Net Profit',today_cuts:"Today's Cuts",
    done_services:'completed services',supplies_bills_sub:'Supplies + Fixed bills',profit_label:'Profit',loss_label:'Loss',
    today_reservations:"Today's Bookings",no_today_reservations:'No bookings today',
    barber_performance:'Barber Performance This Month',no_employees:'No employees',cuts_unit:'cuts',due_commission:'Due Commission',
    popular_services:'Most Requested Services',no_data_yet:'No data yet',times_unit:'times',
    financial_summary:'Financial Summary',month_revenue_summary:'Month Revenue',supplies_cost:'Supplies',fixed_bills_label:'Fixed Bills',
    res_pending:'Pending',res_confirmed:'Confirmed',res_done:'Done',res_cancelled:'Cancelled',
    items_title:'Inventory Items',new_item_btn:'New Item',search_items:'Search by name or code...',all_categories:'All Categories',
    th_category:'Category',th_cost:'Cost Price',th_price:'Selling Price',th_stock:'Stock',th_min_stock:'Min Stock',
    no_items:'No items found',edit_item_title:'Edit Item',add_item_title:'Add New Item',
    lbl_item_code:'Code',lbl_item_name:'Item Name',lbl_item_category:'Category',lbl_item_unit:'Unit',
    lbl_item_cost:'Cost Price',lbl_item_price:'Selling Price',lbl_item_stock:'Current Stock',lbl_item_min:'Min Stock',lbl_item_desc:'Description',
    confirm_delete_item:'Delete this item?',
    invoices_list_title:'Sales Invoice Register',search_invoices:'Search by number or customer...',th_customer:'Customer',th_due:'Due Date',
    confirm_delete_invoice:'Delete this invoice?',no_invoices_list:'No invoices',
    purchases_list_title:'Purchase Register',new_purchase_btn:'New Purchase Invoice',search_purchases:'Search by number or supplier...',
    th_supplier:'Supplier',no_purchases:'No purchase invoices',
    accounts_title:'Chart of Accounts',new_account_btn:'New Account',all_types:'All Types',
    no_accounts:'No accounts found',type_asset:'Asset',type_liability:'Liability',type_equity:"Owner's Equity",type_revenue:'Revenue',type_expense:'Expense',
    lbl_acc_code:'Account Code',lbl_acc_name:'Account Name',lbl_acc_type:'Account Type',lbl_opening_balance:'Opening Balance',new_account_title:'New Account',
    stock_report_title:'Stock Report',total_items_label:'Total Items',total_units_label:'Total Units',
    stock_value_label:'Stock Value',low_stock_label:'Low Stock Items',
    th_opening_stock:'Opening Stock',th_incoming:'In',th_outgoing:'Out',th_current_stock:'Current Stock',th_value:'Value',
    warehouses_title:'Warehouses',new_warehouse_btn:'New Warehouse',no_warehouses:'No warehouses',new_warehouse_title:'New Warehouse',
    lbl_warehouse_name:'Warehouse Name',lbl_location:'Location',lbl_manager:'Manager',
    ledger_title:'Account Ledger',lbl_account:'Account',select_account:'-- Select Account --',from_date:'From Date',view_btn:'View',
    opening_balance_row:'Opening Balance',no_movements:'No transactions in this period',
    trial_balance_title:'Trial Balance',trial_balance_sub:'Trial Balance',total_label:'Total',
    journal_title:'Journal Entries',new_entry_btn:'New Entry',no_entries:'No journal entries',new_entry_title:'New Journal Entry',
    lbl_debit_acc:'Debit Account',lbl_credit_acc:'Credit Account',select_placeholder:'-- Select --',
    receipt_title:'Receipt Voucher',new_receipt_title:'New Receipt Voucher',lbl_voucher_no:'Voucher No.',lbl_received_from:'Received From',
    save_voucher_btn:'Save Voucher',recent_vouchers:'Recent Vouchers',th_from:'From',no_vouchers:'No vouchers',
    payment_title:'Payment Voucher',new_payment_title:'New Payment Voucher',lbl_paid_to:'Paid To',th_to:'To',
    services_title:'Services',new_service_btn:'New Service',th_service:'Service',th_base_price:'Base Price',th_duration:'Duration',
    no_services:'No services',no_services_hint:'Add services like: haircut, beard trim, hair wash',svc_active:'Active',svc_inactive:'Inactive',edit_service_title:'Edit Service',new_service_title:'New Service',
    lbl_service_name:'Service Name',service_name_placeholder:'e.g. Haircut',lbl_base_price:'Base Price ($)',lbl_duration_min:'Duration (min)',min_abbr:'min',
    lbl_junior_price:'Junior Price ($)',lbl_senior_price:'Senior Price ($)',lbl_master_price:'Master Price ($)',
    employees_title:'Employees',new_employee_btn:'New Employee',no_employees_data:'No employees',
    emp_count:'Employee Count',month_cuts:'Month Cuts',month_rev_label:'This Month Revenue',
    th_emp_level:'Level',th_salary_type:'Salary Type',th_base_salary:'Salary',th_commission_pct:'Commission%',th_month_cuts:'Month Cuts',th_due:'Due',
    edit_employee_title:'Edit Employee',new_employee_title:'New Employee',
    lbl_emp_name:'Name',lbl_emp_level:'Level',lbl_salary_type:'Salary Type',lbl_base_salary:'Base Salary ($)',lbl_commission_rate:'Commission Rate (%)',
    salary_commission:'Commission Only',salary_salary_commission:'Salary + Commission',salary_salary:'Fixed Salary',
    reservations_title:'Reservations',search_customer:'Search by customer name...',all_statuses:'All Statuses',
    th_res_customer:'Customer',th_res_service:'Service',th_res_employee:'Barber',th_res_time:'Time',th_res_price:'Price',
    no_reservations:'No reservations',edit_reservation_title:'Edit Booking',new_reservation_title:'New Booking',
    lbl_customer_name:'Customer Name',lbl_service:'Service',lbl_employee:'Barber',lbl_time:'Time',lbl_price:'Price ($)',lbl_notes:'Notes',lbl_status:'Status',
    select_service:'-- Select Service --',select_employee:'-- Select Barber --',
    supplies_title:'Supplies',new_supply_btn:'Add Supply',
    month_supplies:'This Month Expenses',total_supplies:'Total Expenses',supplies_count:'Records',
    th_supply_cat:'Category',no_supplies:'No supplies',new_supply_title:'New Supply',
    lbl_supply_name:'Supply Name',lbl_supply_amount:'Amount ($)',lbl_supply_cat:'Category',lbl_notes_opt:'Notes',
    cat_supply:'Supply',cat_tool:'Tool',cat_product:'Product',cat_other:'Other',
    bills_title:'Fixed Bills',new_bill_btn:'New Bill',
    total_unpaid:'Unpaid',total_paid_label:'Paid',total_bills:'Total Bills',
    th_bill_name:'Bill',th_bill_due_day:'Due Day',th_bill_month:'Month',
    no_bills:'No bills',new_bill_title:'New Bill',
    lbl_bill_name:'Bill Name',lbl_bill_amount:'Amount ($)',lbl_bill_due_day:'Due Day',lbl_bill_month:'Month',
    bill_paid:'Paid',bill_unpaid:'Unpaid',unpay_btn:'Undo Payment',pay_btn:'✅ Pay',
    notify_saved:'Saved successfully ✓',notify_deleted:'Deleted',confirm_delete:'Confirm delete?',
    notify_bill_paid:'Payment confirmed ✅',notify_bill_unpaid:'Payment cancelled',
    notify_voucher_receipt:'Receipt voucher saved',notify_voucher_payment:'Payment voucher saved',
    notify_commission_error:'Error recording commission',notify_commission_saved:'Commission recorded',notify_commission_paid:'Commissions paid ✅',
    notify_item_not_found:'Item not found',notify_points_insufficient:'Insufficient loyalty points',
    notify_doc_saved:'Document saved ✓',notify_reservation_saved:'Booking saved',notify_reservation_done:'Booking completed ✅',
    save_error:'An error occurred while saving',company_saved:'Company settings saved ✅',
    company_settings_title:'Company Settings',save_settings_btn:'Save Settings',
    company_data_section:'Company Information',system_settings_section:'System Settings',
    lbl_company_name_ar:'Company Name (Arabic)',lbl_company_name_en:'Company Name (English)',
    lbl_address:'Address',lbl_phone_settings:'Phone',lbl_email:'Email',lbl_website:'Website',
    lbl_currency:'Default Currency',lbl_tax_rate:'Default Tax Rate (%)',
    lbl_period_start:'Fiscal Period Start',lbl_period_end:'Fiscal Period End',lbl_reg_number:'Registration Number',
    // Doc editor
    doc_info_title:'Document Info',doc_number_label:'Document No.',doc_due_date:'Due Date',
    doc_warehouse:'Warehouse',doc_status:'Status',doc_party_placeholder:'Type customer or supplier name...',
    doc_summary_title:'Document Summary',doc_subtotal:'Subtotal',doc_discount_pct:'Discount %',
    doc_vat_pct:'VAT %',doc_notes_label:'Notes',doc_items_title:'Document Items',doc_add_item:'Add Item',
    doc_type_invoices:'Sales Invoice',doc_type_sales_return:'Sales Return',doc_type_orders:'Order',
    doc_type_purchases:'Purchase Invoice',doc_type_purchases_return:'Purchase Return',
    party_customer:'Customer',party_supplier:'Supplier',doc_party_required:'Please select',
    // POS
    pay_cash_usd:'Cash (USD)',pay_cash_lbp:'Cash (LBP)',pay_card:'Card',pay_loyalty:'Loyalty',
    pos_search_placeholder:'Search by name or barcode...',pos_stock_label:'Stock',
    pos_empty_cart:'Search for an item to add to cart',pos_col_item:'Item',pos_col_qty:'Qty',
    pos_col_discount:'Disc%',pos_customer_label:'Customer',pos_phone_search:'Search by phone...',
    pos_items_count_label:'Items',pos_item_unit:'item',pos_qty_unit:'unit',
    pos_charge_btn:'Charge',pos_payment_title:'Payment',pos_pay_method_label:'Payment Method',
    pos_paid_usd_label:'Amount Paid (USD)',pos_paid_lbp_label:'Amount Paid (LBP)',
    pos_processing:'Processing...',pos_confirm_pay:'Confirm Payment',pos_change_label:'Change',
    pos_success_title:'Transaction Complete',pos_points_earned_label:'points earned',
    pos_cart_empty_error:'Cart is empty',pos_checkout_error:'Checkout error',
  },
  FR: {
    loading:'Chargement...',save_btn:'Enregistrer',cancel_btn:'Annuler',delete_btn:'Supprimer',edit_btn:'Modifier',print_btn:'Imprimer',export_btn:'Exporter',view_all:'Voir tout',no_data:'Aucune donnée',
    status_paid:'Payé',status_unpaid:'Non payé',status_partial:'Partiel',status_cancelled:'Annulé',status_low:'Faible',status_ok:'Disponible',status_active:'Actif',
    pay_cash:'Espèces',pay_bank:'Virement bancaire',pay_check:'Chèque',
    th_number:'Numéro',th_date:'Date',th_total:'Total',th_status:'Statut',th_action:'Action',th_debit:'Débit',th_credit:'Crédit',th_balance:'Solde',th_desc:'Description',th_name:'Nom',th_code:'Code',th_amount:'Montant',th_phone:'Téléphone',
    lbl_date:'Date',lbl_amount:'Montant',lbl_desc:'Description',lbl_name:'Nom',lbl_phone:'Téléphone',
    biz_barber:'Salon de coiffure',biz_retail:'Commerce de détail',logout:'Déconnexion',
    nav_dashboard:'Tableau de bord',nav_services:'Services',nav_employees:'Employés',nav_reservations:'Réservations',
    nav_invoices:'Facture de vente',nav_inv_list:'Registre des factures',nav_sales_return:'Retour de vente',nav_orders:'Commandes',
    nav_purchases_inv:"Facture d'achat",nav_pur_list:'Registre des achats',nav_purchases_return:"Retour d'achat",
    nav_items:'Articles',nav_stock_report:'Rapport de stock',nav_warehouse:'Dépôts',
    nav_accounts:'Plan comptable',nav_ledger:'Grand livre',nav_trial_balance:'Balance',nav_journal_entries:'Écritures',
    nav_supplies:'Fournitures',nav_bills:'Factures fixes',nav_receipt:'Reçu',nav_payment:'Paiement',nav_company_settings:'Paramètres',
    login_subtitle:'Système de gestion commerciale',login_email:'Adresse e-mail',login_password:'Mot de passe',
    login_btn:'Connexion',login_loading:'Connexion en cours...',
    login_error_empty:'Veuillez saisir votre e-mail et mot de passe',login_error_wrong:'E-mail ou mot de passe incorrect',
    dashboard_title:'Tableau de bord',new_invoice_btn:'Nouvelle facture',
    total_revenue:"Chiffre d'affaires",paid_invoices:'Factures payées',inventory_items:'Articles en stock',low_stock_count:'Stock faible',
    stat_rev_sub:'↑ 12% par rapport au mois dernier',total_units_sub:'unités au total',needs_reorder:'À réapprovisionner',out_of:'sur',
    sales_chart_title:'Ventes des 6 derniers mois',low_stock_title:'Articles en rupture de stock',
    stock_ok:'✅ Stock en bon état',recent_invoices_title:'Dernières factures',top_customers_title:'Meilleurs clients',no_invoices:'Aucune facture',
    new_reservation_btn:'Nouvelle réservation',supplies_btn:'Fourniture',
    month_revenue:'Revenus du mois',month_expenses:'Dépenses du mois',net_profit:'Bénéfice net',today_cuts:"Coupes d'aujourd'hui",
    done_services:'services réalisés',supplies_bills_sub:'Fournitures + Factures fixes',profit_label:'Bénéfice',loss_label:'Perte',
    today_reservations:"Réservations d'aujourd'hui",no_today_reservations:"Aucune réservation aujourd'hui",
    barber_performance:'Performance du mois',no_employees:'Aucun employé',cuts_unit:'coupes',due_commission:'Commission due',
    popular_services:'Services les plus demandés',no_data_yet:'Pas encore de données',times_unit:'fois',
    financial_summary:'Résumé financier',month_revenue_summary:'Revenus du mois',supplies_cost:'Fournitures',fixed_bills_label:'Factures fixes',
    res_pending:'En attente',res_confirmed:'Confirmé',res_done:'Terminé',res_cancelled:'Annulé',
    items_title:'Articles en stock',new_item_btn:'Nouvel article',search_items:'Rechercher par nom ou code...',all_categories:'Toutes catégories',
    th_category:'Catégorie',th_cost:"Prix d'achat",th_price:'Prix de vente',th_stock:'Stock',th_min_stock:'Stock min',
    no_items:'Aucun article',edit_item_title:'Modifier article',add_item_title:'Ajouter un article',
    lbl_item_code:'Code',lbl_item_name:"Nom de l'article",lbl_item_category:'Catégorie',lbl_item_unit:'Unité',
    lbl_item_cost:"Prix d'achat",lbl_item_price:'Prix de vente',lbl_item_stock:'Stock actuel',lbl_item_min:'Stock minimum',lbl_item_desc:'Description',
    confirm_delete_item:'Supprimer cet article ?',
    invoices_list_title:'Registre des ventes',search_invoices:'Rechercher par numéro ou client...',th_customer:'Client',th_due:'Échéance',
    confirm_delete_invoice:'Supprimer cette facture ?',no_invoices_list:'Aucune facture',
    purchases_list_title:'Registre des achats',new_purchase_btn:"Nouvelle facture d'achat",search_purchases:'Rechercher par numéro ou fournisseur...',
    th_supplier:'Fournisseur',no_purchases:"Aucune facture d'achat",
    accounts_title:'Plan comptable',new_account_btn:'Nouveau compte',all_types:'Tous les types',
    no_accounts:'Aucun compte',type_asset:'Actif',type_liability:'Passif',type_equity:'Capitaux propres',type_revenue:'Produits',type_expense:'Charges',
    lbl_acc_code:'Code compte',lbl_acc_name:'Nom du compte',lbl_acc_type:'Type de compte',lbl_opening_balance:'Solde initial',new_account_title:'Nouveau compte',
    stock_report_title:'Rapport de stock',total_items_label:'Total articles',total_units_label:'Total unités',
    stock_value_label:'Valeur du stock',low_stock_label:'Stock faible',
    th_opening_stock:'Stock initial',th_incoming:'Entrées',th_outgoing:'Sorties',th_current_stock:'Stock actuel',th_value:'Valeur',
    warehouses_title:'Dépôts',new_warehouse_btn:'Nouveau dépôt',no_warehouses:'Aucun dépôt',new_warehouse_title:'Nouveau dépôt',
    lbl_warehouse_name:'Nom du dépôt',lbl_location:'Lieu',lbl_manager:'Responsable',
    ledger_title:'Grand livre',lbl_account:'Compte',select_account:'-- Sélectionner un compte --',from_date:'Date de début',view_btn:'Afficher',
    opening_balance_row:'Solde initial',no_movements:'Aucune transaction sur cette période',
    trial_balance_title:'Balance générale',trial_balance_sub:'Balance',total_label:'Total',
    journal_title:'Écritures comptables',new_entry_btn:'Nouvelle écriture',no_entries:'Aucune écriture',new_entry_title:'Nouvelle écriture comptable',
    lbl_debit_acc:'Compte débiteur',lbl_credit_acc:'Compte créditeur',select_placeholder:'-- Sélectionner --',
    receipt_title:'Reçu de paiement',new_receipt_title:'Nouveau reçu',lbl_voucher_no:'N° reçu',lbl_received_from:'Reçu de',
    save_voucher_btn:'Enregistrer',recent_vouchers:'Derniers reçus',th_from:'De',no_vouchers:'Aucun reçu',
    payment_title:'Bon de paiement',new_payment_title:'Nouveau bon de paiement',lbl_paid_to:'Payé à',th_to:'À',
    services_title:'Services',new_service_btn:'Nouveau service',th_service:'Service',th_base_price:'Prix de base',th_duration:'Durée',
    no_services:'Aucun service',no_services_hint:'Ajoutez vos services : coupe, rasage, lavage',svc_active:'Actif',svc_inactive:'Inactif',edit_service_title:'Modifier service',new_service_title:'Nouveau service',
    lbl_service_name:'Nom du service',service_name_placeholder:'ex: Coupe',lbl_base_price:'Prix de base ($)',lbl_duration_min:'Durée (min)',min_abbr:'min',
    lbl_junior_price:'Prix Junior ($)',lbl_senior_price:'Prix Senior ($)',lbl_master_price:'Prix Master ($)',
    employees_title:'Employés',new_employee_btn:'Nouvel employé',no_employees_data:'Aucun employé',
    emp_count:"Nombre d'employés",month_cuts:'Coupes du mois',month_rev_label:'Revenus du mois',
    th_emp_level:'Niveau',th_salary_type:'Type de salaire',th_base_salary:'Salaire',th_commission_pct:'Commission%',th_month_cuts:'Coupes du mois',th_due:'Dû',
    edit_employee_title:'Modifier employé',new_employee_title:'Nouvel employé',
    lbl_emp_name:'Nom',lbl_emp_level:'Niveau',lbl_salary_type:'Type de salaire',lbl_base_salary:'Salaire de base ($)',lbl_commission_rate:'Taux de commission (%)',
    salary_commission:'Commission uniquement',salary_salary_commission:'Salaire + Commission',salary_salary:'Salaire fixe',
    reservations_title:'Réservations',search_customer:'Rechercher par client...',all_statuses:'Tous les statuts',
    th_res_customer:'Client',th_res_service:'Service',th_res_employee:'Coiffeur',th_res_time:'Heure',th_res_price:'Prix',
    no_reservations:'Aucune réservation',edit_reservation_title:'Modifier réservation',new_reservation_title:'Nouvelle réservation',
    lbl_customer_name:'Nom du client',lbl_service:'Service',lbl_employee:'Coiffeur',lbl_time:'Heure',lbl_price:'Prix ($)',lbl_notes:'Notes',lbl_status:'Statut',
    select_service:'-- Sélectionner service --',select_employee:'-- Sélectionner coiffeur --',
    supplies_title:'Fournitures',new_supply_btn:'Ajouter',
    month_supplies:'Dépenses du mois',total_supplies:'Total dépenses',supplies_count:'Enregistrements',
    th_supply_cat:'Catégorie',no_supplies:'Aucune fourniture',new_supply_title:'Nouvelle fourniture',
    lbl_supply_name:'Nom',lbl_supply_amount:'Montant ($)',lbl_supply_cat:'Catégorie',lbl_notes_opt:'Notes',
    cat_supply:'Fourniture',cat_tool:'Outil',cat_product:'Produit',cat_other:'Autre',
    bills_title:'Factures fixes',new_bill_btn:'Nouvelle facture',
    total_unpaid:'Non payé',total_paid_label:'Payé',total_bills:'Total factures',
    th_bill_name:'Facture',th_bill_due_day:"Jour d'échéance",th_bill_month:'Mois',
    no_bills:'Aucune facture',new_bill_title:'Nouvelle facture',
    lbl_bill_name:'Nom de la facture',lbl_bill_amount:'Montant ($)',lbl_bill_due_day:"Jour d'échéance",lbl_bill_month:'Mois',
    bill_paid:'Payé',bill_unpaid:'Non payé',unpay_btn:'Annuler paiement',pay_btn:'✅ Payer',
    notify_saved:'Enregistré ✓',notify_deleted:'Supprimé',confirm_delete:'Confirmer la suppression ?',
    notify_bill_paid:'Paiement confirmé ✅',notify_bill_unpaid:'Paiement annulé',
    notify_voucher_receipt:'Reçu enregistré',notify_voucher_payment:'Bon de paiement enregistré',
    notify_commission_error:'Erreur enregistrement commission',notify_commission_saved:'Commission enregistrée',notify_commission_paid:'Commissions payées ✅',
    notify_item_not_found:'Article introuvable',notify_points_insufficient:'Points insuffisants',
    notify_doc_saved:'Document enregistré ✓',notify_reservation_saved:'Réservation enregistrée',notify_reservation_done:'Réservation terminée ✅',
    save_error:'Une erreur est survenue lors de la sauvegarde',company_saved:'Paramètres enregistrés ✅',
    company_settings_title:"Paramètres de l'entreprise",save_settings_btn:'Enregistrer',
    company_data_section:'Informations entreprise',system_settings_section:'Paramètres système',
    lbl_company_name_ar:'Nom (arabe)',lbl_company_name_en:'Nom (anglais)',
    lbl_address:'Adresse',lbl_phone_settings:'Téléphone',lbl_email:'E-mail',lbl_website:'Site web',
    lbl_currency:'Devise par défaut',lbl_tax_rate:'Taux de taxe (%)',
    lbl_period_start:'Début de période',lbl_period_end:'Fin de période',lbl_reg_number:"Numéro d'enregistrement",
    // Doc editor
    doc_info_title:'Info document',doc_number_label:'N° document',doc_due_date:"Date d'échéance",
    doc_warehouse:'Dépôt',doc_status:'Statut',doc_party_placeholder:'Tapez le nom du client ou fournisseur...',
    doc_summary_title:'Résumé document',doc_subtotal:'Sous-total',doc_discount_pct:'Remise %',
    doc_vat_pct:'TVA %',doc_notes_label:'Notes',doc_items_title:'Articles du document',doc_add_item:'Ajouter un article',
    doc_type_invoices:'Facture de vente',doc_type_sales_return:'Retour de vente',doc_type_orders:'Bon de commande',
    doc_type_purchases:"Facture d'achat",doc_type_purchases_return:"Retour d'achat",
    party_customer:'Client',party_supplier:'Fournisseur',doc_party_required:'Veuillez sélectionner',
    // POS
    pay_cash_usd:'Espèces (USD)',pay_cash_lbp:'Espèces (LBP)',pay_card:'Carte',pay_loyalty:'Fidélité',
    pos_search_placeholder:'Rechercher par nom ou code-barres...',pos_stock_label:'Stock',
    pos_empty_cart:'Recherchez un article à ajouter',pos_col_item:'Article',pos_col_qty:'Qté',
    pos_col_discount:'Rem%',pos_customer_label:'Client',pos_phone_search:'Rechercher par téléphone...',
    pos_items_count_label:'Articles',pos_item_unit:'article',pos_qty_unit:'unité',
    pos_charge_btn:'Encaisser',pos_payment_title:'Paiement',pos_pay_method_label:'Mode de paiement',
    pos_paid_usd_label:'Montant payé (USD)',pos_paid_lbp_label:'Montant payé (LBP)',
    pos_processing:'Traitement...',pos_confirm_pay:'Confirmer le paiement',pos_change_label:'Rendu',
    pos_success_title:'Transaction réussie',pos_points_earned_label:'points gagnés',
    pos_cart_empty_error:'Panier vide',pos_checkout_error:'Erreur de paiement',
  },
}
