export const DOC_TYPES = {
  invoices:          { label_ar:'فاتورة مبيع',      label_en:'Sales Invoice',      prefix:'INV', store:'invoices',      partyLabel_ar:'العميل',  partyLabel_en:'Customer',  icon:'🧾', parties:['شركة الأمل التجارية','مؤسسة النجاح','شركة الخليج','محلات السعادة','مجموعة الفجر','التجارية للأعمال'] },
  'sales-return':    { label_ar:'مرتجع مبيعات',     label_en:'Sales Return',       prefix:'SR',  store:'salesReturns',  partyLabel_ar:'العميل',  partyLabel_en:'Customer',  icon:'↩️', parties:['شركة الأمل التجارية','مؤسسة النجاح','شركة الخليج','محلات السعادة'] },
  orders:            { label_ar:'طلبية',             label_en:'Order',              prefix:'ORD', store:'orders',        partyLabel_ar:'العميل',  partyLabel_en:'Customer',  icon:'📑', parties:['شركة الأمل التجارية','مؤسسة النجاح','شركة الخليج','محلات السعادة'] },
  purchases:         { label_ar:'فاتورة شراء',       label_en:'Purchase Invoice',   prefix:'PUR', store:'purchases',     partyLabel_ar:'المورد',  partyLabel_en:'Supplier',  icon:'🛒', parties:['مورد الإلكترونيات','مورد القرطاسية','مورد الأثاث','مورد المعدات'] },
  'purchases-return':{ label_ar:'مرتجع مشتريات',    label_en:'Purchase Return',    prefix:'PR',  store:'purchReturns',  partyLabel_ar:'المورد',  partyLabel_en:'Supplier',  icon:'↩️', parties:['مورد الإلكترونيات','مورد القرطاسية','مورد الأثاث'] },
}

export const SIDEBAR_MENUS = {
  barber: [
    { icon:'📊', label:'لوحة التحكم',     page:'dashboard' },
    { icon:'✂️', label:'الخدمات',         page:'services' },
    { icon:'👥', label:'الموظفون',         page:'employees' },
    { icon:'📅', label:'الحجوزات',         page:'reservations' },
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'🧴', label:'المستلزمات',       page:'supplies' },
    { icon:'💡', label:'الفواتير الثابتة', page:'bills' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
  building_materials: [
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'↩️', label:'مرتجع مبيعات',    page:'sales-return' },
    { icon:'🛒', label:'فاتورة شراء',      page:'purchases' },
    { icon:'📋', label:'سجل المشتريات',    page:'purchases-list' },
    { icon:'↩️', label:'مرتجع مشتريات',   page:'purchases-return' },
    { icon:'📦', label:'أصناف',            page:'items' },
    { icon:'📒', label:'دليل الحسابات',    page:'accounts' },
    { icon:'🔍', label:'كشف حساب',         page:'account-ledger' },
    { icon:'⚖️', label:'ميزان المراجعة',   page:'trial-balance' },
    { icon:'✏️', label:'القيود المحاسبية', page:'journal-entries' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
  auto_parts: [
    { icon:'📊', label:'لوحة التحكم',      page:'dashboard' },
    { icon:'🧾', label:'فاتورة مبيع',      page:'invoices' },
    { icon:'📋', label:'سجل الفواتير',     page:'invoices-list' },
    { icon:'↩️', label:'مرتجع مبيعات',    page:'sales-return' },
    { icon:'📑', label:'طلبيات',           page:'orders' },
    { icon:'🛒', label:'فاتورة شراء',      page:'purchases' },
    { icon:'📋', label:'سجل المشتريات',    page:'purchases-list' },
    { icon:'↩️', label:'مرتجع مشتريات',   page:'purchases-return' },
    { icon:'📦', label:'أصناف',            page:'items' },
    { icon:'📈', label:'كشف المخزون',      page:'stock-report' },
    { icon:'🏭', label:'المخازن',          page:'warehouse' },
    { icon:'📒', label:'دليل الحسابات',    page:'accounts' },
    { icon:'🔍', label:'كشف حساب',         page:'account-ledger' },
    { icon:'⚖️', label:'ميزان المراجعة',   page:'trial-balance' },
    { icon:'✏️', label:'القيود المحاسبية', page:'journal-entries' },
    { icon:'💵', label:'سند قبض',          page:'receipt-voucher' },
    { icon:'💸', label:'سند صرف',          page:'payment-voucher' },
    { icon:'🏢', label:'بيانات الشركة',    page:'company-settings' },
  ],
}

export const i18n = {
  AR: { nav_main:'الرئيسية',nav_dashboard:'لوحة التحكم',nav_sales:'المبيعات',nav_invoices:'فاتورة مبيع',nav_inv_list:'سجل الفواتير',nav_sales_return:'مرتجع مبيعات',nav_orders:'طلبيات',nav_purchases:'المشتريات',nav_purchases_inv:'فاتورة شراء',nav_pur_list:'سجل المشتريات',nav_purchases_return:'مرتجع مشتريات',nav_stock:'المخزن',nav_items:'أصناف',nav_stock_report:'كشوفات الأصناف',nav_warehouse:'المخازن',nav_accounting:'المحاسبة',nav_accounts:'دليل الحسابات',nav_ledger:'كشف حساب',nav_trial_balance:'ميزان المراجعة',nav_journal_entries:'القيود المحاسبية',nav_receipt:'سند قبض',nav_payment:'سند صرف',dashboard_title:'لوحة التحكم',new_invoice_btn:'فاتورة جديدة',sales_chart_title:'مبيعات الأشهر الستة',low_stock_title:'أصناف منخفضة',view_all:'عرض الكل',recent_invoices_title:'آخر الفواتير',top_customers_title:'أكبر العملاء',items_title:'أصناف المخزون',new_item_btn:'صنف جديد',export_btn:'تصدير',th_code:'كود',th_name:'اسم الصنف',th_category:'الفئة',th_cost:'سعر الشراء',th_price:'سعر البيع',th_stock:'المخزون',th_min_stock:'الحد الأدنى',th_status:'الحالة',th_action:'إجراء',invoices_list_title:'سجل فواتير المبيع',subtitle:'للتجارة العامة' },
  EN: { nav_main:'Main',nav_dashboard:'Dashboard',nav_sales:'Sales',nav_invoices:'Sales Invoice',nav_inv_list:'Invoice Register',nav_sales_return:'Sales Return',nav_orders:'Orders',nav_purchases:'Purchases',nav_purchases_inv:'Purchase Invoice',nav_pur_list:'Purchase Register',nav_purchases_return:'Purchase Return',nav_stock:'Inventory',nav_items:'Items',nav_stock_report:'Stock Report',nav_warehouse:'Warehouses',nav_accounting:'Accounting',nav_accounts:'Chart of Accounts',nav_ledger:'Ledger',nav_trial_balance:'Trial Balance',nav_journal_entries:'Journal Entries',nav_receipt:'Receipt Voucher',nav_payment:'Payment Voucher',dashboard_title:'Dashboard',new_invoice_btn:'New Invoice',sales_chart_title:'Last 6 Months Sales',low_stock_title:'Low Stock Items',view_all:'View All',recent_invoices_title:'Recent Invoices',top_customers_title:'Top Customers',items_title:'Inventory Items',new_item_btn:'New Item',export_btn:'Export',th_code:'Code',th_name:'Item Name',th_category:'Category',th_cost:'Cost Price',th_price:'Selling Price',th_stock:'Stock',th_min_stock:'Min Stock',th_status:'Status',th_action:'Action',invoices_list_title:'Sales Invoice Register',subtitle:'General Trading' },
  FR: { nav_main:'Principal',nav_dashboard:'Tableau de bord',nav_sales:'Ventes',nav_invoices:'Facture de vente',nav_inv_list:'Registre des factures',nav_sales_return:'Retour de vente',nav_orders:'Commandes',nav_purchases:'Achats',nav_purchases_inv:"Facture d'achat",nav_pur_list:'Registre des achats',nav_purchases_return:"Retour d'achat",nav_stock:'Stock',nav_items:'Articles',nav_stock_report:'Rapport de stock',nav_warehouse:'Dépôts',nav_accounting:'Comptabilité',nav_accounts:'Plan comptable',nav_ledger:'Grand livre',nav_trial_balance:'Balance',nav_journal_entries:'Écritures',nav_receipt:'Reçu',nav_payment:'Paiement',dashboard_title:'Tableau de bord',new_invoice_btn:'Nouvelle facture',sales_chart_title:'Ventes 6 mois',low_stock_title:'Stock faible',view_all:'Voir tout',recent_invoices_title:'Dernières factures',top_customers_title:'Meilleurs clients',items_title:'Articles en stock',new_item_btn:'Nouvel article',export_btn:'Exporter',th_code:'Code',th_name:'Article',th_category:'Catégorie',th_cost:'Prix achat',th_price:'Prix vente',th_stock:'Stock',th_min_stock:'Stock min',th_status:'Statut',th_action:'Action',invoices_list_title:'Registre des ventes',subtitle:'Commerce Général' },
}
